/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negocio.DTOS.PermisoDTO;
import Negocio.Servicios.PermisoServicio;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prueba
 */
public class Gestion extends javax.swing.JFrame {

    static DefaultTableModel modeloPermisos;

    /**
     * Creates new form Gestion
     */
    public Gestion() {
        initComponents();
        setearModeloTablaPermisos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPermisos = new javax.swing.JTable();
        Aceptar = new javax.swing.JButton();
        Rechazar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.I", "Rol", "Aplicativo", "Estado"
            }
        ));
        tablaPermisos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tablaPermisos);
        tablaPermisos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Rechazar.setText("Rechazar");
        Rechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(Rechazar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        int cedula = Integer.parseInt(tablaPermisos.getValueAt(tablaPermisos.getSelectedRow(), 0).toString());
        int rol = Integer.parseInt(tablaPermisos.getValueAt(tablaPermisos.getSelectedRow(), 1).toString());
        int app = Integer.parseInt(tablaPermisos.getValueAt(tablaPermisos.getSelectedRow(), 2).toString());
        PermisoDTO permiso = PermisoServicio.updatePermisoAceptado(cedula, rol, app);
        try {
            //vaciar tabla
            cargarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(Gestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void RechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechazarActionPerformed
        int cedula = Integer.parseInt(tablaPermisos.getValueAt(tablaPermisos.getSelectedRow(), 0).toString());
        int rol = Integer.parseInt(tablaPermisos.getValueAt(tablaPermisos.getSelectedRow(), 1).toString());
        int app = Integer.parseInt(tablaPermisos.getValueAt(tablaPermisos.getSelectedRow(), 2).toString());
        try {
            PermisoDTO permiso = PermisoServicio.updatePermisoRechazado(cedula, rol, app);

            /* String permisoId = rows.toString();
            System.out.print(permisoId);                            // ver esto como verga
            // ver como hacer para que seleccione la id del permiso
            PermisoDTO permiso = PermisoServicio.getPermisoById(Integer.parseInt(permisoId));
            permiso.Estado = "rechazado";
            //modeloPermisos.removeRow(rows[i]-i); se borra la row desp de rechazada o noo?*/
        } catch (SQLException ex) {
            Logger.getLogger(Gestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            //vaciar tabla
            cargarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(Gestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RechazarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            cargarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(Gestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Gestion().setVisible(true);

        });

    }

    private void cargarTabla() throws SQLException {
        PermisoDTO[] permisos = PermisoServicio.getPermisos();

        for (PermisoDTO p : permisos) {

            String[] texto = new String[4];

            texto[0] = String.valueOf(p.UserId);
            texto[1] = String.valueOf(p.RolNegId);
            texto[2] = String.valueOf(p.AppId);
            texto[3] = p.Estado;

            modeloPermisos.addRow(texto);
        }

    }

    private void setearModeloTablaPermisos() {
        modeloPermisos = new DefaultTableModel();
        modeloPermisos.addColumn("C.I");
        modeloPermisos.addColumn("Rol");
        modeloPermisos.addColumn("Aplicativo");
        modeloPermisos.addColumn("Estado");

        //modeloProcesos.addColumn("RAM (MB)");
        this.tablaPermisos.setModel(modeloPermisos);
        this.tablaPermisos.setCellSelectionEnabled(false);
        this.tablaPermisos.setRowSelectionAllowed(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Rechazar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPermisos;
    // End of variables declaration//GEN-END:variables
}
